---
version: '2'
services:
  web:
    build: .
    image: 'dansnow/juice'
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - './conf:/conf'
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql
    env_file: web.env
  redis:
    image: 'redis:3-alpine'
  mysql:
    image: 'mariadb'
    env_file: mysql.env
